name: CD Pipeline

on:
  push:
    branches:
      - develop

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Tag Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |
            my-image:${{ github.sha }}
            my-image:latest

      - name: Scan Docker Image with Snyk
        run: snyk container test my-image:${{ github.sha }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            my-image:${{ github.sha }}
            my-image:latest

      - name: Save Docker Image to DockerHub
        uses: docker/save-image-action@v1
        with:
          name: my-image:${{ github.sha }}
          path: my-image.tar

      - name: Update Kubernetes Manifests
        run: |
          sed -i "s/image: my-image:.*/image: my-image:${{ github.sha }}/g" kubernetes/deployment.yaml
          sed -i "s/tag:.*/tag: ${{ github.sha }}/g" helm/values.yaml

      - name: Log Pipeline Status
        run: echo "CD pipeline completed successfully."

